export const store = {
  brandName: "Health Product",
  legalBusinessName: null as string | null,
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ?? "",
  displayBrandNameMs: "Kesihatan Lelaki",
  contactEmail: "producth006@gmail.com",
  phone: null as string | null,
  whatsappNumber: null as string | null,
  address: null as string | null,
  logoPath: null as string | null,
  heroImagePath: "/home-couple.webp" as string | null,
  socialLinks: {
    instagram: null as string | null,
    facebook: null as string | null,
    tiktok: null as string | null,
  },
  priceCurrency: "MYR",
  deliveryFee: 0,
  deliveryLabel: "Free delivery across Malaysia",
  deliveryCoverage: "Free delivery is offered across Malaysia, including West Malaysia, Sabah and Sarawak.",
  deliveryTimingNote: "Delivery timing depends on destination and courier service. Our team will confirm your order and delivery details.",
  codAvailable: true,
  codRequiresDestinationConfirmation: true,
  codLabel: "Cash on Delivery",
  codAvailabilityNote: "Cash on Delivery is available. Final availability may depend on your destination and courier service; our team will confirm before dispatch.",
  codConfirmationLabel: "I understand that Cash on Delivery availability depends on my destination and courier service.",
  discreetPackagingConfirmed: false,
};

export const malaysianStates = [
  "Johor",
  "Kedah",
  "Kelantan",
  "Kuala Lumpur",
  "Labuan",
  "Melaka",
  "Negeri Sembilan",
  "Pahang",
  "Penang",
  "Perak",
  "Perlis",
  "Putrajaya",
  "Sabah",
  "Sarawak",
  "Selangor",
  "Terengganu",
] as const;

export const malaysianStatesMs = [
  "Johor",
  "Kedah",
  "Kelantan",
  "Kuala Lumpur",
  "Labuan",
  "Melaka",
  "Negeri Sembilan",
  "Pahang",
  "Pulau Pinang",
  "Perak",
  "Perlis",
  "Putrajaya",
  "Sabah",
  "Sarawak",
  "Selangor",
  "Terengganu",
] as const;
